parameters:
- name: pool
  type: object
- name: varFile
  type: string
- name: variableGroup
  type: string
- name: environment
  type: string
- name: sensitiveVariableNames # use this to reference secret names from a variable group
  type: object
  default: {}

jobs:
- deployment: Apply
  displayName: Apply
  pool:
    ${{ parameters.pool }}
  variables:
    - group: ${{ parameters.variableGroup }}
  environment: ${{ parameters.environment }}
  timeoutInMinutes: "60"
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            clean: true
          - bash: |
              cd environments
              go test -v -timeout 60m
            env:
              VARFILE: ${{ parameters.varFile }}
              TF_PLAN: "false"
              TF_APPLY: "true"
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ${{ insert }}: ${{ parameters.sensitiveVariableNames }}
            displayName: 'Apply'