parameters:
- name: pool
  type: object
- name: varFile
  type: string
- name: variableGroup
  type: string
- name: sensitiveVariableNames # use this to reference secret names from a variable group
  type: object
  default: {}

jobs:
- job: CI
  displayName: CI
  pool:
    ${{ parameters.pool }}
  variables:
    - group: ${{ parameters.variableGroup }}
  workspace:
    clean: all
  timeoutInMinutes: "60"
  steps:
    - bash: |
        cd environments
        go test -v -timeout 60m
      env:
        VARFILE: ${{ parameters.varFile }}
        TF_PLAN: "true"
        TF_APPLY: "true"
        TF_DESTROY: "true"
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ${{ insert }}: ${{ parameters.sensitiveVariableNames }}
      displayName: 'CI'