steps:
  - script: |
      echo "Installing Checkov..."
      echo "##[command]pip3 install checkov"
      pip3 install checkov==3.2.31
      echo "##[command]checkov --version"
      checkov --version
    displayName: 'Install Checkov'
