parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
    - Dev
    - Test
    - Prod

variables:
- group: Terraform ${{ parameters.environment }}
- name: environment
  value: ${{ lower(parameters.environment) }}
- name: workingDirectory
  value: $(Build.Repository.LocalPath)/modules/node-app-service

pr: none

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - modules/**
    exclude:
    - '**/README.md'

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: Validate
    jobs:
    - job: Validate
      steps:
      # Checkout repo
      - checkout: self
        displayName: 'Checkout Repo'

      # Install required packages
      - template: steps/install-tflint.yaml
      - template: steps/install-checkov.yaml

      # Login to Azure using Terraform service principal
      - template: steps/azure-login.yaml

      # Run terraform init
      - template: steps/terraform-init.yaml
        parameters:
          environment: ${{ variables.environment }}
          workingDirectory: ${{ variables.workingDirectory }}

      # Run Terraform format
      - template: steps/terraform-format.yaml
        parameters:
          workingDirectory: ${{ variables.workingDirectory }}

      # Run Terraform validate
      - template: steps/terraform-validate.yaml
        parameters:
          workingDirectory: ${{ variables.workingDirectory }}

      # Run TFLint
      - template: steps/tflint-validate.yaml
        parameters:
          configFilePath: $(Build.Repository.LocalPath)/.tflint.hcl
          workingDirectory: ${{ variables.workingDirectory }}

      # Run Checkov
      - template: steps/checkov-validate.yaml
        parameters:
          framework: terraform
          workingDirectory: ${{ variables.workingDirectory }}
